# Market Configuration for PSE-LLM Trading System
# Defines market-specific parameters, sessions, and trading rules

# Market Sessions
sessions:
  rth:
    name: "Regular Trading Hours"
    start: "09:30"
    end: "16:00"
    timezone: "America/New_York"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

  eth:
    name: "Extended Trading Hours"
    start: "18:00"
    end: "17:00"  # Next day
    timezone: "America/New_York"
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

  twenty_four_hour:
    name: "24/7 Trading"
    start: "00:00"
    end: "23:59"
    timezone: "UTC"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

# Symbol Definitions
symbols:
  # Equity Index Futures
  es:
    name: "E-mini S&P 500 Futures"
    exchange: "CME"
    currency: "USD"
    tick_size: 0.25
    point_value: 50.0
    initial_margin: 1320.0
    maintenance_margin: 1200.0
    session: "rth"
    trading_hours: "09:30-16:00 ET"
    contract_months: ["H", "M", "U", "Z"]  # Mar, Jun, Sep, Dec
    max_order_size: 100
    min_order_size: 1

  nq:
    name: "E-mini NASDAQ 100 Futures"
    exchange: "CME"
    currency: "USD"
    tick_size: 0.25
    point_value: 20.0
    initial_margin: 2640.0
    maintenance_margin: 2400.0
    session: "rth"
    trading_hours: "09:30-16:00 ET"
    contract_months: ["H", "M", "U", "Z"]
    max_order_size: 50
    min_order_size: 1

  rty:
    name: "E-mini Russell 2000 Futures"
    exchange: "CME"
    currency: "USD"
    tick_size: 0.10
    point_value: 50.0
    initial_margin: 1584.0
    maintenance_margin: 1440.0
    session: "rth"
    trading_hours: "09:30-16:00 ET"
    contract_months: ["H", "M", "U", "Z"]
    max_order_size: 100
    min_order_size: 1

  # Interest Rate Futures
  zn:
    name: "10-Year T-Note Futures"
    exchange: "CBOT"
    currency: "USD"
    tick_size: 0.015625
    point_value: 1000.0
    initial_margin: 1485.0
    maintenance_margin: 1350.0
    session: "rth"
    trading_hours: "08:00-15:00 ET"
    contract_months: ["H", "M", "U", "Z"]
    max_order_size: 50
    min_order_size: 1

  zf:
    name: "5-Year T-Note Futures"
    exchange: "CBOT"
    currency: "USD"
    tick_size: 0.0078125
    point_value: 1000.0
    initial_margin: 1155.0
    maintenance_margin: 1050.0
    session: "rth"
    trading_hours: "08:00-15:00 ET"
    contract_months: ["H", "M", "U", "Z"]
    max_order_size: 50
    min_order_size: 1

  # Commodity Futures
  gc:
    name: "Gold Futures"
    exchange: "COMEX"
    currency: "USD"
    tick_size: 0.10
    point_value: 100.0
    initial_margin: 7920.0
    maintenance_margin: 7200.0
    session: "eth"
    trading_hours: "18:00-17:00 ET"
    contract_months: ["G", "J", "M", "Q", "V", "Z"]  # Feb, Apr, Jun, Aug, Oct, Dec
    max_order_size: 30
    min_order_size: 1

  si:
    name: "Silver Futures"
    exchange: "COMEX"
    currency: "USD"
    tick_size: 0.005
    point_value: 5000.0
    initial_margin: 9900.0
    maintenance_margin: 9000.0
    session: "eth"
    trading_hours: "18:00-17:00 ET"
    contract_months: ["H", "K", "N", "U", "Z"]  # Mar, May, Jul, Sep, Dec
    max_order_size: 20
    min_order_size: 1

  cl:
    name: "WTI Crude Oil Futures"
    exchange: "NYMEX"
    currency: "USD"
    tick_size: 0.01
    point_value: 1000.0
    initial_margin: 5775.0
    maintenance_margin: 5250.0
    session: "eth"
    trading_hours: "18:00-17:00 ET"
    contract_months: ["G", "J", "K", "M", "N", "Q", "U", "V", "X", "Z"]
    max_order_size: 50
    min_order_size: 1

# Exchange Information
exchanges:
  cme:
    name: "Chicago Mercantile Exchange"
    timezone: "America/Chicago"
    trading_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    holiday_schedule_url: "https://www.cmegroup.com/tools-information/holiday-calendar.html"

  cbot:
    name: "Chicago Board of Trade"
    timezone: "America/Chicago"
    trading_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    holiday_schedule_url: "https://www.cmegroup.com/tools-information/holiday-calendar.html"

  comex:
    name: "Commodity Exchange"
    timezone: "America/New_York"
    trading_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    holiday_schedule_url: "https://www.cmegroup.com/tools-information/holiday-calendar.html"

  nymex:
    name: "New York Mercantile Exchange"
    timezone: "America/New_York"
    trading_days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    holiday_schedule_url: "https://www.cmegroup.com/tools-information/holiday-calendar.html"

# Market Hours and Sessions
market_hours:
  # Futures markets typically have different hours
  futures:
    pre_open: "08:00"
    open: "09:30"
    close: "16:00"
    after_hours: "16:00-18:00"
    eth_start: "18:00"
    eth_end: "17:00"  # Next day

  # Equity markets
  equities:
    pre_market: "04:00"
    open: "09:30"
    close: "16:00"
    after_hours: "16:00-20:00"

# Volatility and Liquidity Profiles
market_profiles:
  es:
    avg_daily_volume: 1500000
    avg_spread_ticks: 0.75
    volatility_profile: "medium"
    liquidity_profile: "high"
    typical_gap_pct: 0.002

  nq:
    avg_daily_volume: 800000
    avg_spread_ticks: 1.25
    volatility_profile: "high"
    liquidity_profile: "high"
    typical_gap_pct: 0.003

  rty:
    avg_daily_volume: 400000
    avg_spread_ticks: 0.5
    volatility_profile: "high"
    liquidity_profile: "medium"
    typical_gap_pct: 0.004

  gc:
    avg_daily_volume: 150000
    avg_spread_ticks: 0.25
    volatility_profile: "medium"
    liquidity_profile: "high"
    typical_gap_pct: 0.005

  si:
    avg_daily_volume: 80000
    avg_spread_ticks: 0.1
    volatility_profile: "high"
    liquidity_profile: "medium"
    typical_gap_pct: 0.008

  cl:
    avg_daily_volume: 600000
    avg_spread_ticks: 0.15
    volatility_profile: "high"
    liquidity_profile: "high"
    typical_gap_pct: "0.015"

# Contract Specifications
contract_specs:
  es:
    contract_size: 1
    contract_unit: "E-mini S&P 500 Index"
    price_quote: "Index Points"
    minimum_tick: 0.25
    tick_value: 12.50
    trading_unit: "1 contract = $50 × S&P 500 Index"

  nq:
    contract_size: 1
    contract_unit: "E-mini NASDAQ 100 Index"
    price_quote: "Index Points"
    minimum_tick: 0.25
    tick_value: 5.00
    trading_unit: "1 contract = $20 × NASDAQ 100 Index"

  gc:
    contract_size: 100
    contract_unit: "Troy Ounces"
    price_quote: "USD per Troy Ounce"
    minimum_tick: 0.10
    tick_value: 10.00
    trading_unit: "1 contract = 100 troy ounces"

  cl:
    contract_size: 1000
    contract_unit: "U.S. Barrels"
    price_quote: "USD per Barrel"
    minimum_tick: 0.01
    tick_value: 10.00
    trading_unit: "1 contract = 1,000 barrels"

# Market Data Providers
data_providers:
  databento:
    supported_symbols: ["es", "nq", "rty", "gc", "si", "cl", "zn", "zf"]
    data_types: ["trades", "quotes", "order_book", "imbalances"]
    latency: "low"
    cost: "medium"

  polygon:
    supported_symbols: ["es", "nq", "rty"]
    data_types: ["trades", "quotes", "aggregates"]
    latency: "medium"
    cost: "low"

  ibkr:
    supported_symbols: ["all"]
    data_types: ["trades", "quotes", "order_book", "news", "fundamentals"]
    latency: "medium"
    cost: "low"

# Commission and Fees
fees:
  ibkr:
    commission_per_contract:
      es: 0.25
      nq: 0.25
      rty: 0.25
      gc: 0.25
      si: 0.25
      cl: 0.25
    exchange_fees:
      es: 0.05
      nq: 0.05
      rty: 0.05
      gc: 0.05
      si: 0.05
      cl: 0.05
    clearing_fees:
      es: 0.02
      nq: 0.02
      rty: 0.02
      gc: 0.02
      si: 0.02
      cl: 0.02

# Risk Parameters by Symbol
risk_parameters:
  es:
    volatility_lookback: 20
    atr_period: 14
    typical_stop_distance: 8.0
    max_position_size: 10

  nq:
    volatility_lookback: 20
    atr_period: 14
    typical_stop_distance: 20.0
    max_position_size: 5

  gc:
    volatility_lookback: 20
    atr_period: 14
    typical_stop_distance: 2.0
    max_position_size: 3

  cl:
    volatility_lookback: 20
    atr_period: 14
    typical_stop_distance: 1.5
    max_position_size: 5