# Risk Policies Configuration for PSE-LLM Trading System
# Defines risk limits, guards, and policy gates for all trading activities

# Position Sizing and Risk Limits
position_sizing:
  method: "fixed_risk"  # Options: fixed_risk, kelly, volatility_based
  account_risk_pct: 0.01  # 1% account risk per trade
  min_r_multiplier: 1.5  # Minimum R:R ratio required
  max_r_multiplier: 5.0  # Maximum R:R ratio allowed
  kelly_fraction: 0.5  # Fraction of Kelly criterion to use (if method=kelly)

# Universal Stop Loss Caps (points)
sl_caps:
  es: 8.0    # E-mini S&P 500 Futures
  nq: 20.0   # E-mini NASDAQ 100 Futures
  rty: 6.0   # E-mini Russell 2000 Futures
  gc: 2.0    # Gold Futures
  si: 0.5    # Silver Futures
  cl: 1.5    # Crude Oil Futures

# Risk Limits
risk_limits:
  max_r_per_trade: 0.01      # 1% max risk per trade
  max_daily_loss: 0.03       # 3% max daily loss
  max_weekly_loss: 0.05      # 5% max weekly loss
  max_monthly_loss: 0.10     # 10% max monthly loss
  max_drawdown: 0.15         # 15% max drawdown
  max_concurrent_risk: 0.05  # 5% max concurrent risk exposure
  max_trades_per_day: 6      # Maximum trades per day
  max_correlation_risk: 0.7  # Max correlation between concurrent positions

# Execution Guards
execution_guards:
  spread_tolerance:
    es: 0.5   # Max spread in ticks
    nq: 1.0
    rty: 0.3
    gc: 0.1
    si: 0.05
    cl: 0.2

  latency_threshold_ms: 100  # Max round-trip latency
  min_volume_threshold: 100  # Min volume for execution
  max_slippage_pct: 0.001   # Max slippage as percentage

# News and Economic Event Blackout
news_blackout:
  enabled: true
  periods:
    - start: "08:00"
      end: "09:30"
      timezone: "America/New_York"
      reason: "Economic data releases and market open"
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

    - start: "15:55"
      end: "16:05"
      timezone: "America/New_York"
      reason: "Daily economic data releases"
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

  # High-impact event blackout (extend 30 minutes before/after)
  high_impact_events:
    blackout_before_minutes: 30
    blackout_after_minutes: 30
    events:
      - "FOMC announcements"
      - "Non-farm payrolls"
      - "GDP reports"
      - "Interest rate decisions"

# Cool-off and Recovery Rules
cool_off_rules:
  after_loss:
    enabled: true
    bars: 2  # Wait 2 bars after any loss
    consecutive_losses:
      2: 5   # After 2 consecutive losses, wait 5 bars
      3: 10  # After 3 consecutive losses, wait 10 bars
      5: 30  # After 5 consecutive losses, stop for day

  after_large_win:
    enabled: true
    threshold_r: 3.0  # After win > 3R
    bars: 3  # Wait 3 bars

  daily_loss_limit:
    enabled: true
    reset_time: "16:00"  # Reset at market close
    timezone: "America/New_York"

# Market Condition Guards
market_condition_guards:
  high_volatility:
    enabled: true
    atr_threshold: 2.0  # 2x average ATR
    action: "reduce_size"  # reduce_size, skip, or alert
    size_reduction: 0.5

  low_liquidity:
    enabled: true
    volume_threshold: 0.5  # 50% of average volume
    action: "skip"

  gap_threshold:
    enabled: true
    max_gap_pct: 0.02  # 2% max gap
    action: "alert"

# Time-based Restrictions
time_restrictions:
  rth_only: false  # Allow extended hours trading
  min_trading_time: "09:30"
  max_trading_time: "16:00"
  timezone: "America/New_York"

  # Days of week
  trading_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

  # Holiday blackout (dates when markets are closed)
  holidays:
    - "2024-01-01"  # New Year's Day
    - "2024-01-15"  # MLK Day
    - "2024-02-19"  # Presidents Day
    - "2024-03-24"  # Good Friday
    - "2024-05-27"  # Memorial Day
    - "2024-06-19"  # Juneteenth
    - "2024-07-04"  # Independence Day
    - "2024-09-02"  # Labor Day
    - "2024-11-28"  # Thanksgiving
    - "2024-12-25"  # Christmas

# Position Management
position_management:
  max_positions: 3  # Maximum concurrent positions
  max_positions_per_symbol: 1  # Max positions per symbol
  min_time_between_trades: 5  # Min bars between trades for same symbol

  # Partial exit rules
  partial_exits:
    enabled: true
    rules:
      - at_r_multiple: 1.0
        exit_pct: 0.5
        reason: "Take half profits at 1R"
      - at_r_multiple: 2.0
        exit_pct: 0.3
        reason: "Take additional profits at 2R"
      - at_r_multiple: 3.0
        exit_pct: 0.2
        reason: "Take remaining profits at 3R"

# Risk Assessment Weights
risk_weights:
  sl_distance: 0.3      # Weight for stop loss distance
  spread_cost: 0.2      # Weight for spread cost
  market_volatility: 0.2  # Weight for current volatility
  account_balance: 0.15   # Weight for account health
  win_rate: 0.15        # Weight for recent performance

# Emergency Stops
emergency_stops:
  enabled: true
  conditions:
    - name: "Daily Loss Limit"
      threshold: 0.03  # 3% daily loss
      action: "stop_trading"
      reset: "daily"

    - name: "Weekly Loss Limit"
      threshold: 0.05  # 5% weekly loss
      action: "stop_trading"
      reset: "weekly"

    - name: "Drawdown Limit"
      threshold: 0.15  # 15% drawdown
      action: "stop_trading"
      reset: "manual"

# Monitoring and Alerts
monitoring:
  enabled: true
  alert_thresholds:
    large_loss: 2.0  # Alert on losses > 2R
    consecutive_losses: 3  # Alert after 3 consecutive losses
    high_frequency: 10  # Alert if > 10 trades in 30 minutes

  # Alert channels (webhook URLs, email, etc.)
  alert_channels:
    - type: "log"
      level: "WARNING"
    - type: "console"
      enabled: true

# Compliance and Regulatory
compliance:
  enabled: true
  rules:
    - name: "Pattern Day Trading"
      description: "Monitor day trading patterns"
      threshold: 4  # Max day trades for pattern day trader
      action: "restrict_trading"

    - name: "Concentration Risk"
      description: "Limit exposure to single symbol"
      max_exposure_pct: 0.25  # Max 25% in single symbol
      action: "reduce_position"

# A+ Quality Assessment Gates
quality_gates:
  enabled: true
  min_mqs_score: 7.0  # Minimum Market Quality Score
  min_frs_score: 7.0  # Minimum Fair Value Gap Score
  require_tcc_confirmation: true
  require_mcs_alignment: true

  # Quality-based sizing adjustments
  sizing_multipliers:
    a_plus: 1.0    # Full size for A+ setups
    a: 0.75        # 75% size for A setups
    b: 0.5         # 50% size for B setups
    c: 0.25        # 25% size for C setups
    fail: 0.0      # Skip for failing setups